.TH p3d_odol2mlod 1 "February 2026" "arma-tools" "User Commands"
.SH NAME
p3d_odol2mlod \- convert binarized ODOL P3D models to MLOD
.SH SYNOPSIS
.B p3d_odol2mlod
.I path/model.p3d
.br
.B p3d_odol2mlod
.I inputFolder
.RI [ outputFolder ]
.SH DESCRIPTION
.B p3d_odol2mlod
converts ODOL models (Arma and OFP/CWA variants) into editable MLOD files.
.SH NOTES
This tool does not expose a full option parser; usage is positional only.
.SH SEE ALSO
.BR p3d_info (1)
