.TH paa2tga 1 "February 2026" "arma-tools" "User Commands"
.SH NAME
paa2tga \- convert PAA/PAC textures to TGA
.SH SYNOPSIS
.B paa2tga
.RI [ flags ]
.I input.paa|input.pac
.SH DESCRIPTION
.B paa2tga
converts a PAA/PAC file to TGA.
.SH OPTIONS
.TP
.BI "-o " path
Output TGA path.
.TP
.BR -h , " --help"
Show help.
.SH SEE ALSO
.BR tga2paa (1),
.BR paa2img (1)
